MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_USER: root
MYSQL_PASSWD : root
MYSQL_DB: py_mysql
MYSQL_CAHRSET: utf8
SQLALCHEMY_DATABASE_URL : mysql+pymysql://root:root@localhost:3306/py_mysql?charset=utf8

LOGIN:
  yzkj:
   LOGIN_USERNAME: yzkj
   LOGIN_PASSWORD: 123456
   LOGIN_DISABLED_STATUS: True
  zlx:
   LOGIN_USERNAME: zlx
   LOGIN_PASSWORD: 123456
   LOGIN_DISABLED_STATUS: False
